# action.yml
name: "Terraform Plan"
description: "Accepts path to terraform configurations to run commands within directory."
inputs:
  TFPATH:
    description: "Path to terraform files."
    required: true
  REGION:
    description: "Region to execute terraform commands against."
    required: true
  ACTION:
    description: "Terraform action to perform."
    required: true
  ACCESS_TOKEN:
    description: "Token used to authenticate to the GitHub API for commenting on PRs."
    required: true
  REPO_OWNER:
    description: "Used to build the PR URL dynamically."
    required: true
  REPO_NAME:
    description: "Used to build the PR URL dynamically."
    required: true
  IS_MANUAL:
    description: "Used to define if this is a manual run."
    required: false
  SLACK_WEBHOOK_URL:
    description: "Used in tandem with IS_MANUAL. Used to alert on destructive actions."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.TFPATH }}
    - ${{ inputs.REGION }}
    - ${{ inputs.ACTION }}
    - ${{ inputs.ACCESS_TOKEN }}
    - ${{ inputs.REPO_OWNER }}
    - ${{ inputs.REPO_NAME }}
    - ${{ inputs.IS_MANUAL }}
    - ${{ inputs.SLACK_WEBHOOK_URL }}
